git:
  depth: 100

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
  fast_finish: true

env:
  global:
    - CC_ENV=travis-ci

  # matrix:
  #   - CC_BOOT=default

before_install:
  - antcc/bootstrap/install.sh
  - . $HOME/.bash_profile

script:
  - antcc boot -Daccept.license=true
  - antcc up test

cache:
  directories:
    - $HOME/Downloads
