version: '3.2'
services:
  cc:
    image: ${REG}/commandcentral-server:$TAG
    ports:
      - 8091:8091
      - 8092:8092
    environment:
      - CC_PASSWORD
  init:
    image: ${REG}/commandcentral-client:$TAG
    volumes:
      - ./:/src
      - ./clients/docker.properties:/root/.sag/cc.properties
    environment:
      - CC_SERVER=cc
      - CC_ENV
      - CC_PASSWORD
      - EMPOWER_USR
      - EMPOWER_PSW
    command: ant up clean
    depends_on:
      - cc
