version: '3.2'
services:
  cc:
    image: ${CC_REG}/commandcentral-server:$CC_TAG
    ports:
      - 8091:8091
      - 8092:8092
    # environment:
    #   - CC_PASSWORD
  init:
    image: ${CC_REG}/commandcentral-client:$CC_TAG
    volumes:
      - ./:/src
#      - ./clients/docker.properties:/root/.sag/cc.properties
    environment:
      - CC_SERVER=cc
      - CC_ENV
      - EMPOWER_USR
      - EMPOWER_PSW
      # - CC_PASSWORD
    command: ant up test clean
    depends_on:
      - cc
